[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
spin = "0.9"
sbi-rt = "0.0.3"
buddy_system_allocator = "0.9.0"

[build-dependencies]
regex = "1.10.5"